### ISSUE TITLE
Introduce best practices document

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/ids-specification#104]
Following [ODRL best practices](https://w3c.github.io/odrl/bp/), we should add a document that briefly explains how the protocol could/should be used and how it could be extended, state machine- or vocabulary-wise (on an abstract level). This will help people to understand the intention and scope of these documents beyond the basic [README.md](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/README.md).

Possible ToC:
- Introduction
- How to use
- How to extend the negotiation process (e.g., human processes)
- How to extend the transfer process
- How to extend types
   - How to define custom properties 
   - When to introduce own messages
- How to write your own binding

**Comment by jimmarino** [comment]
There appear to be a few issues here:

1. A primer covering the DSP protocol
2. The process for writing binding specifications
3. How to "extend" the DSP protocol

Point 1 could be done by the RAM or another set of documents and they should be explicitly non-normative. @PeterKoen-MSFT, what do you think?

Point 2 is important, but I don't think we should define it at this point because that process will depend on the standards body we submit the current specifications to.

IMO we should never define #3. Conformant implementations are not required to support extending the protocol with custom messages or types, and that touches too much on specific implementation details. It will also break interoperability. If people want to "extend" the protocol, they should create overlay or derivative protocols outside the requirements of the core specifications in a different working group.  

Implementations should also not be required to support human workflows. The only capability they should be required to support is the asynchronous messaging specified by the protocol. 

Note that this is different than saying people should avoid developing policy or catalog vocabularies.  We don't need to do anything, as ODRL and DCAT already define ways of doing this.

**Comment by gbrost** [comment]
I would really like to see good practices how to embed the protocol in real data space implementations. 
This should include
- Authentication
- Authorization
- Transport security, encryption

**Comment by ssteinbuss** [comment]
* Include in this repo and add as non-normative to the GitBook thing. 

* Mention important aspects, that are not part of the Protocol, but a Dataspace needs to solve

* link to other available resources
