### ISSUE TITLE
Discuss impact of 'compactArrays' in JsonLD

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#125]
I learned arrays with only 1 element can automatically be processed by the jsonld libs into single objects.
jsonld:
https://www.w3.org/TR/json-ld-api/#the-jsonldoptions-type

Also discussed in EDC here:
https://github.com/eclipse-edc/Connector/issues/3232
and answered there:
https://github.com/eclipse-edc/Connector/issues/3137#issuecomment-1572028156

This is also relevant for what we discussed here already regarding policy property:
https://github.com/International-Data-Spaces-Association/ids-specification/issues/76

Questions are:
- is this desired behavior?
- what is the effect on provided schemas?

--
Matthias Binzer

**Comment by matgnt** [comment]
Decision in the meeting today:
- jsonld serialization in compact form, with compactArrays=False (meaning, arrays are arrays also with only a single element)
https://www.w3.org/TR/json-ld-api/#the-jsonldoptions-type
- required profiling jsonld, needs to be a separate section
- also move other profile things (odrl target, etc) into this new profile section (which is in catalog right now)

Also note:
- a property that has not a value it is not included in the message (MUST). empty array means no value, means not included.

**Comment by matgnt** [comment]
Probably also jsonld related, the timestamp field sometimes is a string (EDC implementation) and sometimes an object with `@type` and `@value` (here in the spec)

**Comment by sebbader-sap** [comment]
Currently the following options are possible:

1. "simple string option":
```
"dspace:timestamp":"2023-01-01T01:00:00Z"
```
Problem: Value is not typed, not self-described. Not how JSON-LD should do it (I mean, that's why we went for JSON-LD and not plain JSON, right? :-))

2. XSD Literal:
```
"dspace:timestamp": {
      "@value": "2023-01-01T01:00:00Z",
      "@type": "xsd:dateTime"
    }
```
Problem: Requires an enabled parser (as any real JSON-LD parser can do), time zone might be missed

3. XSD Literal but with Time Zone required:
```
"dspace:timestamp": {
      "@value": "2023-01-01T01:00:00Z",
      "@type": "xsd:dateTimeStamp"
    }
```
See: https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp
Problem: Same as 2. just that the time zone is included for sure. Furthermore, dateTimeStamp is part of XML Schema 1.1, which is not necessarily known to all implementations (different to XML Schema 1.0 with dateTime)

4. OWL Time (as demanded by DCAT):
![image](https://github.com/International-Data-Spaces-Association/ids-specification/assets/107036549/edc1f746-386c-4d77-b4e6-fa6f8296dba4)
See: https://www.w3.org/TR/owl-time/#time:Instant 
Problem: complete overkill

5. others?


My preference is option 2 (as a Literal with xsd:dateTime) as it's the best compromise of expressivity and added attributes. If the time zone is not stated, UTC is meant.
