### ISSUE TITLE
Context File is returned with the Mimetype "plain/text"

### ISSUE THREAD

**Issue by sebbader-sap** [International-Data-Spaces-Association/ids-specification#171]
... however, "application/json" or "application/ld+json" is required.

**Comment by sebbader-sap** [comment]
@mkollenstart I just tested the JSON-LD messages with Jena, which worked out-of-the-box. Looks like at least Jena doesn't give much about the mime type when resolving the context.

**Comment by mkollenstart** [comment]
Since Gtihub Pages actions only support pushing a single artifact, the only viable solution is to include the releases into the repository.
I've created a fork with an example of how this could work at https://github.com/mkollenstart/ids-specification where I've created a `releases` folder and a Gtihub Action for creating the Github pages.
The JSON-LD context can then be accessed via https://mkollenstart.github.io/ids-specification/0.8/schema/context.json 

The repository settings should then be updated to use Github Actions as source for Github Pages (In Settings > Code and automation > Pages > Source).

The question is how to serve the working version (i.e. the non-released version) of the context, should that be in a folder within releases or in the current directory structure? For the latter the github action should be updated to include those files in the Github Pages.

_Note_: The next two weeks I'm out of office, so feel free to merge these changes without me.

**Comment by sebbader-sap** [comment]
I also need the following three JSON files being exposed the same way:

* https://raw.githubusercontent.com/International-Data-Spaces-Association/ids-specification/main/negotiation/message/schema/contract-schema.json 
* https://raw.githubusercontent.com/International-Data-Spaces-Association/ids-specification/main/catalog/message/schema/catalog-schema.json
* https://raw.githubusercontent.com/International-Data-Spaces-Association/ids-specification/main/catalog/message/schema/dataset-schema.json

**Comment by ssteinbuss** [comment]
We wait for @mkollenstart
